# src/utils/lang_pt.py

TEXTOS_PT = {
    "painel_principal": "Painel Principal",
    "balanco_geral": "Balanço Geral",
    "diag_financeiro": "Diagnóstico Financeiro",
    "investimentos": "Investimentos",
    "area_educacao": "Área de Educação",
    "metas_financeiras": "Metas Financeiras",
    "lembretes_contas": "Lembretes de Contas",
    "editar_perfil": "Editar Perfil",
    "btn_sair": "Sair",
    "aviso": "Aviso",
    "erro": "Erro",
    "sucesso": "Sucesso",
    "titulo_login": "Bem vindo ao EasyFinance",
    "subtitulo_login": "Acesse sua Conta Corporativa",
    "campo_email": "Digite seu e-mail:",
    "campo_senha": "Digite sua senha:",
    "mostrar_senha": "Mostrar Senha",
    "btn_entrar": "Entrar no Painel",
    "saldo_atual": "Saldo Atual",
    "receitas_mes": "Receitas do Mês",
    "despesas_mes": "Despesas do Mês",
    "desempenho_b2b": "Seu Desempenho B2B",
    "pontuacao_tecnica": "Sua Pontuação Técnica",
    "nivel_perfil": "Nível do Perfil",
    "controle_teto_gastos": "Controle de Teto de Gastos (Budgeting)",
    "nenhum_gasto_monitoramento": "Nenhum gasto registrado para monitoramento de teto.",
    "orcamento_estourado": "⚠️ ORÇAMENTO ESTOURADO!",
    "proximo_limite": "🟡 Próximo ao Limite",
    "dentro_do_teto": "🟢 Dentro do Teto",
    "alerta_oportunidade_1": "Alerta de Custo de Oportunidade: Sua empresa possui",
    "alerta_oportunidade_2": "parados em caixa.",
    "alerta_oportunidade_3": "Investir o excesso",
    "alerta_oportunidade_4": "evitaria uma perda estimada de",
    "fluxo_caixa": "Fluxo de Caixa e Transações",
    "nenhuma_transacao": "Nenhuma transação registrada.",
    "nova_movimentacao": "Nova Movimentação",
    "desc_exemplo": "Descrição (Ex: Marketing)",
    "valor_exemplo": "Valor (Ex: 1500.00)",
    "btn_registrar": "Registrar",
    "msg_preencha_dados": "Preencha a descrição e o valor.",
    "msg_transacao_ok": "Transação registrada!",
    "msg_erro_valor": "Insira um valor numérico válido.",
    "saude_relatorio": "Relatório de Saúde Financeira",
    "status_atual": "Status Atual:",
    "status_saudavel": "SAUDÁVEL 🟢",
    "msg_saudavel": "Parabéns! Sua empresa está operando no azul.\nRecomendação: Considere investir o dinheiro excedente para criar uma reserva de emergência.",
    "status_alerta": "EM ALERTA 🔴",
    "msg_alerta": "Atenção! Sua empresa está gastando mais do que arrecada.\nRecomendação: Revise a aba de 'Balanço Geral' e corte despesas não essenciais imediatamente.",
    "status_estavel": "ESTÁVEL 🟡",
    "msg_estavel": "Sua empresa não tem lucros nem prejuízos no momento.\nRecomendação: Foque em aumentar as vendas ou criar novas fontes de receita.",
    "titulo_educacao": "EasyFinance Academy - 20 Cursos Disponíveis",
    "btn_assistir": "Assistir",
    "titulo_metas": "Metas e Objetivos do Negócio",
    "nenhuma_meta": "Nenhuma meta cadastrada.",
    "alvo_meta": "Alvo",
    "nova_meta": "Nova Meta",
    "ex_meta_obj": "Ex: Novo Servidor",
    "ex_meta_val": "Ex: 5000.00",
    "btn_add_meta": "Adicionar Meta",
    "msg_preencha_meta": "Preencha o objetivo e o valor da meta.",
    "msg_meta_add": "Meta financeira adicionada!",
    "titulo_lembretes": "Lembretes de Contas a Pagar",
    "nenhum_lembrete": "Nenhum compromisso agendado.",
    "vence_em": "Vence em",
    "novo_lembrete": "Novo Lembrete",
    "ex_conta": "Ex: Conta de Luz",
    "ex_data": "Ex: 10/06/2026",
    "btn_agendar": "Agendar Conta",
    "msg_preencha_campos": "Preencha os campos.",
    "msg_lembrete_add": "Lembrete agendado!",
    "config_conta": "Configurações da Conta",
    "lbl_email": "E-mail (Login):",
    "lbl_doc": "Documento (CNPJ/CPF):",
    "lbl_nova_senha": "Nova Senha:",
    "btn_salvar_perfil": "Salvar Alterações",
    "msg_senha_branco": "A senha não pode ficar em branco.",
    "msg_perfil_ok": "Perfil atualizado!",
    "titulo_investimentos": "💹 Investimentos Corporativos",
    "lbl_usd": "Dólar (USD)",
    "carregando": "Carregando...",
    "lbl_eur": "Euro (EUR)",
    "registro_aquisicao": "Registrar Nova Aquisição",
    "selecione_ativo": "Selecione o Ativo:",
    "preco_unitario": "Preço Unitário do Ativo (R$):",
    "saldo_calculando": "Saldo disponível: Calculando...",
    "qtd_comprar": "Quantidade a Comprar:",
    "ex_qtd": "Ex: 50",
    "btn_qtd_max": "Preencher Quantidade Máxima",
    "btn_confirmar_inv": "Confirmar Investimento",
    "conversor_moedas": "💱 Conversor de Moedas Comercial",
    "ph_valor_brl": "Valor em Reais (R$)",
    "resultado_conv": "Resultado: ---",
    "btn_calcular_conv": "Calcular Conversão",
    "carteira_ativos": "📊 Sua Carteira de Ativos",
    "btn_rebalancear": "⚖️ Verificar Rebalanceamento (Metas)",
    "btn_exportar_rel": "📥 Exportar Relatório Patrimonial",
    "saldo_txt": "Saldo:",
    "max_permitido": "Máximo permitido:",
    "offline": "Offline",
    "erro_api": "Erro API",
    "erro_conv_off": "Erro: Conversor indisponível (Offline)",
    "msg_insira_brl": "Insira um valor em Reais para efetuar a conversão.",
    "resultado_txt": "Resultado:",
    "msg_erro_num": "Digite apenas caracteres numéricos válidos no conversor.",
    "rebalanceamento": "Rebalanceamento",
    "msg_carteira_vazia": "Sua carteira está vazia! Sugestão: Comece aportando igualmente em USD e EUR.",
    "msg_erro_rebal_api": "Não é possível rebalancear sem acesso às cotações de mercado.",
    "meta_cumprida_tit": "⚖️ Meta Cumprida!",
    "msg_meta_cumprida": "Sua carteira está perfeitamente balanceada de acordo com as diretrizes!",
    "distribuicao_atual": "Distribuição Atual:",
    "sugestao_rebal_tit": "⚖️ Sugestão de Rebalanceamento",
    "msg_desvio_detect": "Desvio detectado das diretrizes ideais de alocação de risco (50%/50%).",
    "alocacao_atual": "Alocação Atual:",
    "recomendacao_rebal": "Recomendação: Direcione os próximos aportes para adquirir",
    "msg_erro_ativo_api": "Ativo ou cotação da API inválidos.",
    "msg_preencha_tudo": "Preencha todos os campos do formulário!",
    "msg_qtd_maior_zero": "A quantidade precisa ser maior que zero!",
    "saldo_insuficiente_tit": "Saldo Insuficiente",
    "msg_saldo_insuf": "Você não possui saldo em conta para esta operação!",
    "custo_total": "Custo Total:",
    "msg_ativo_comprado": "Ativo comprado!",
    "valor_debitado": "Valor debitado da conta:",
    "msg_erro_num_qtd": "Digite apenas números válidos no campo de Quantidade!",
    "msg_carteira_vazia_label": "Nenhum ativo comprado ainda.",
    "pago": "Pago:",
    "total": "Total:",
    "relatorio_gerado_tit": "Relatório Gerado",
    "msg_relatorio_salvo": "O relatório foi salvo em seu Desktop.",
    "msg_enviar_email": "Deseja enviar uma cópia para o e-mail:",
    "btn_enviando_email": "📨 Enviando E-mail...",
    "msg_email_enviado": "Relatório enviado com sucesso para",
    "erro_envio_tit": "Erro de Envio",
    "msg_erro_envio": "O arquivo foi salvo localmente, mas não pôde ser enviado por e-mail:",
    "concluido": "Concluído",
    "msg_relatorio_disp": "O relatório está disponível em:",
    "erro_exportacao_tit": "Erro de Exportação",
    "msg_aguarde_api": "Aguarde o carregamento das cotações da API.", 
    "msg_adicional": "⚠️ Atenção: Como a data informada já passou, o lembrete foi marcado como 'Vencido' e uma multa de R$ {VALOR_MULTA:.2f} foi debitada do seu saldo!"
}