# src/utils/lang_en.py

TEXTOS_EN = {
    "painel_principal": "Main Dashboard",
    "balanco_geral": "General Balance",
    "diag_financeiro": "Financial Diagnosis",
    "investimentos": "Investments",
    "area_educacao": "Education Area",
    "metas_financeiras": "Financial Goals",
    "lembretes_contas": "Bill Reminders",
    "editar_perfil": "Edit Profile",
    "btn_sair": "Sign Out",
    "aviso": "Warning",
    "erro": "Error",
    "sucesso": "Success",
    "titulo_login": "Welcome to EasyFinance",
    "subtitulo_login": "Access your Corporate Account",
    "campo_email": "Enter your email:",
    "campo_senha": "Enter your password:",
    "mostrar_senha": "Show Password",
    "btn_entrar": "Sign In",
    "saldo_atual": "Current Balance",
    "receitas_mes": "Monthly Revenue",
    "despesas_mes": "Monthly Expenses",
    "desempenho_b2b": "Your B2B Performance",
    "pontuacao_tecnica": "Your Technical Score",
    "nivel_perfil": "Profile Level",
    "controle_teto_gastos": "Budget Limit Control",
    "nenhum_gasto_monitoramento": "No expenses registered for budget monitoring.",
    "orcamento_estourado": "⚠️ BUDGET EXCEEDED!",
    "proximo_limite": "🟡 Near Limit",
    "dentro_do_teto": "🟢 Within Limit",
    "alerta_oportunidade_1": "Opportunity Cost Alert: Your company has",
    "alerta_oportunidade_2": "idle in cash.",
    "alerta_oportunidade_3": "Investing the surplus",
    "alerta_oportunidade_4": "would prevent an estimated loss of",
    "fluxo_caixa": "Cash Flow and Transactions",
    "nenhuma_transacao": "No transactions registered.",
    "nova_movimentacao": "New Transaction",
    "desc_exemplo": "Description (Ex: Marketing)",
    "valor_exemplo": "Amount (Ex: 1500.00)",
    "btn_registrar": "Register",
    "msg_preencha_dados": "Fill in the description and amount.",
    "msg_transacao_ok": "Transaction registered!",
    "msg_erro_valor": "Enter a valid numeric value.",
    "saude_relatorio": "Financial Health Report",
    "status_atual": "Current Status:",
    "status_saudavel": "HEALTHY 🟢",
    "msg_saudavel": "Congratulations! Your company is in the green.\nRecommendation: Consider investing surplus cash to build an emergency fund.",
    "status_alerta": "ON ALERT 🔴",
    "msg_alerta": "Warning! Your company is spending more than it earns.\nRecommendation: Check 'General Balance' and cut non-essential expenses.",
    "status_estavel": "STABLE 🟡",
    "msg_estavel": "Your company has no profit or loss currently.\nRecommendation: Focus on increasing sales or creating new revenue streams.",
    "titulo_educacao": "EasyFinance Academy - 20 Available Courses",
    "btn_assistir": "Watch",
    "titulo_metas": "Business Goals & Targets",
    "nenhuma_meta": "No goals registered.",
    "alvo_meta": "Target",
    "nova_meta": "New Goal",
    "ex_meta_obj": "Ex: New Server",
    "ex_meta_val": "Ex: 5000.00",
    "btn_add_meta": "Add Goal",
    "msg_preencha_meta": "Fill in the goal objective and value.",
    "msg_meta_add": "Financial goal added!",
    "titulo_lembretes": "Bill Reminders",
    "nenhum_lembrete": "No upcoming bills.",
    "vence_em": "Due on",
    "novo_lembrete": "New Reminder",
    "ex_conta": "Ex: Electricity Bill",
    "ex_data": "Ex: 10/06/2026",
    "btn_agendar": "Schedule Bill",
    "msg_preencha_campos": "Please fill in all fields.",
    "msg_lembrete_add": "Reminder scheduled!",
    "config_conta": "Account Settings",
    "lbl_email": "Email (Login):",
    "lbl_doc": "Document (ID):",
    "lbl_nova_senha": "New Password:",
    "btn_salvar_perfil": "Save Changes",
    "msg_senha_branco": "Password cannot be empty.",
    "msg_perfil_ok": "Profile updated!",
    "titulo_investimentos": "💹 Corporate Investments",
    "lbl_usd": "Dollar (USD)",
    "carregando": "Loading...",
    "lbl_eur": "Euro (EUR)",
    "registro_aquisicao": "Register New Acquisition",
    "selecione_ativo": "Select Asset:",
    "preco_unitario": "Asset Unit Price ($):",
    "saldo_calculando": "Available balance: Calculating...",
    "qtd_comprar": "Quantity to Buy:",
    "ex_qtd": "Ex: 50",
    "btn_qtd_max": "Fill Maximum Quantity",
    "btn_confirmar_inv": "Confirm Investment",
    "conversor_moedas": "💱 Commercial Currency Converter",
    "ph_valor_brl": "Amount in BRL (R$)",
    "resultado_conv": "Result: ---",
    "btn_calcular_conv": "Calculate Conversion",
    "carteira_ativos": "📊 Your Asset Portfolio",
    "btn_rebalancear": "⚖️ Check Rebalancing (Goals)",
    "btn_exportar_rel": "📥 Export Wealth Report",
    "saldo_txt": "Balance:",
    "max_permitido": "Max allowed:",
    "offline": "Offline",
    "erro_api": "API Error",
    "erro_conv_off": "Error: Converter unavailable (Offline)",
    "msg_insira_brl": "Enter an amount in BRL to convert.",
    "resultado_txt": "Result:",
    "msg_erro_num": "Enter only valid numeric characters in the converter.",
    "rebalanceamento": "Rebalancing",
    "msg_carteira_vazia": "Your portfolio is empty! Tip: Start by investing equally in USD and EUR.",
    "msg_erro_rebal_api": "Cannot rebalance without access to market quotes.",
    "meta_cumprida_tit": "⚖️ Goal Achieved!",
    "msg_meta_cumprida": "Your portfolio is perfectly balanced according to the guidelines!",
    "distribuicao_atual": "Current Distribution:",
    "sugestao_rebal_tit": "⚖️ Rebalancing Suggestion",
    "msg_desvio_detect": "Deviation detected from ideal risk allocation guidelines (50%/50%).",
    "alocacao_atual": "Current Allocation:",
    "recomendacao_rebal": "Recommendation: Direct your next investments to acquire",
    "msg_erro_ativo_api": "Invalid asset or API quote.",
    "msg_preencha_tudo": "Fill in all form fields!",
    "msg_qtd_maior_zero": "Quantity must be greater than zero!",
    "saldo_insuficiente_tit": "Insufficient Balance",
    "msg_saldo_insuf": "You do not have enough balance for this operation!",
    "custo_total": "Total Cost:",
    "msg_ativo_comprado": "Asset purchased!",
    "valor_debitado": "Amount debited from account:",
    "msg_erro_num_qtd": "Enter only valid numbers in the Quantity field!",
    "msg_carteira_vazia_label": "No assets purchased yet.",
    "pago": "Paid:",
    "total": "Total:",
    "relatorio_gerado_tit": "Report Generated",
    "msg_relatorio_salvo": "The report was saved on your Desktop.",
    "msg_enviar_email": "Would you like to send a copy to the email:",
    "btn_enviando_email": "📨 Sending Email...",
    "msg_email_enviado": "Report successfully sent to",
    "erro_envio_tit": "Sending Error",
    "msg_erro_envio": "The file was saved locally but could not be emailed:",
    "concluido": "Completed",
    "msg_relatorio_disp": "The report is available at:",
    "erro_exportacao_tit": "Export Error",
    "msg_aguarde_api": "Please wait for API quotes to load."
}