# src/utils/lang_es.py

TEXTOS_ES = {
    "painel_principal": "Panel Principal",
    "balanco_geral": "Balance General",
    "diag_financeiro": "Diagnóstico Financiero",
    "investimentos": "Inversiones",
    "area_educacao": "Área de Educación",
    "metas_financeiras": "Metas Financieras",
    "lembretes_contas": "Recordatorios de Cuentas",
    "editar_perfil": "Editar Perfil",
    "btn_sair": "Salir",
    "aviso": "Aviso",
    "erro": "Error",
    "sucesso": "Éxito",
    "titulo_login": "Bienvenido a EasyFinance",
    "subtitulo_login": "Acceda a su Cuenta Corporativa",
    "campo_email": "Ingrese su correo electrónico:",
    "campo_senha": "Ingrese su contraseña:",
    "mostrar_senha": "Mostrar Contraseña",
    "btn_entrar": "Iniciar Sesión",
    "saldo_atual": "Saldo Actual",
    "receitas_mes": "Ingresos del Mes",
    "despesas_mes": "Gastos del Mes",
    "desempenho_b2b": "Su Rendimiento B2B",
    "pontuacao_tecnica": "Su Puntuación Técnica",
    "nivel_perfil": "Nivel del Perfil",
    "controle_teto_gastos": "Control de Límite de Presupuesto",
    "nenhum_gasto_monitoramento": "No hay gastos registrados para monitoreo.",
    "orcamento_estourado": "⚠️ ¡PRESUPUESTO SUPERADO!",
    "proximo_limite": "🟡 Cerca del Límite",
    "dentro_do_teto": "🟢 Dentro del Límite",
    "alerta_oportunidade_1": "Alerta de Costo de Oportunidad: Su empresa tiene",
    "alerta_oportunidade_2": "ociosos en efectivo.",
    "alerta_oportunidade_3": "Invertir el excedente",
    "alerta_oportunidade_4": "evitaría una pérdida estimada de",
    "fluxo_caixa": "Flujo de Caja y Transacciones",
    "nenhuma_transacao": "No hay transacciones registradas.",
    "nova_movimentacao": "Nueva Transacción",
    "desc_exemplo": "Descripción (Ej: Marketing)",
    "valor_exemplo": "Monto (Ej: 1500.00)",
    "btn_registrar": "Registrar",
    "msg_preencha_dados": "Complete la descripción y el monto.",
    "msg_transacao_ok": "¡Transacción registrada!",
    "msg_erro_valor": "Ingrese un valor numérico válido.",
    "saude_relatorio": "Informe de Salud Financiera",
    "status_atual": "Estado Actual:",
    "status_saudavel": "SALUDABLE 🟢",
    "msg_saudavel": "¡Felicidades! Su empresa está operando en verde.\nRecomendación: Considere invertir el efectivo excedente para crear un fondo de emergencia.",
    "status_alerta": "EN ALERTA 🔴",
    "msg_alerta": "¡Atención! Su empresa gasta más de lo que ingresa.\nRecomendación: Revise la pestaña 'Balance General' y recorte gastos no esenciales de inmediato.",
    "status_estavel": "ESTABLE 🟡",
    "msg_estavel": "Su empresa no tiene ganancias ni pérdidas actualmente.\nRecomendación: Concéntrese en aumentar las ventas o crear nuevas fuentes de ingresos.",
    "titulo_educacao": "EasyFinance Academy - 20 Cursos Disponibles",
    "btn_assistir": "Ver",
    "titulo_metas": "Metas y Objetivos Comerciales",
    "nenhuma_meta": "No hay metas registradas.",
    "alvo_meta": "Objetivo",
    "nova_meta": "Nueva Meta",
    "ex_meta_obj": "Ej: Nuevo Servidor",
    "ex_meta_val": "Ej: 5000.00",
    "btn_add_meta": "Añadir Meta",
    "msg_preencha_meta": "Complete el objetivo y el valor de la meta.",
    "msg_meta_add": "¡Meta financiera añadida!",
    "titulo_lembretes": "Recordatorios de Cuentas",
    "nenhum_lembrete": "No hay cuentas pendientes.",
    "vence_em": "Vence el",
    "novo_lembrete": "Nuevo Recordatorio",
    "ex_conta": "Ej: Factura de Luz",
    "ex_data": "Ej: 10/06/2026",
    "btn_agendar": "Programar Cuenta",
    "msg_preencha_campos": "Por favor, complete todos los campos.",
    "msg_lembrete_add": "¡Recordatorio programado!",
    "config_conta": "Configuraciones de la Cuenta",
    "lbl_email": "Correo (Login):",
    "lbl_doc": "Documento (Identidad):",
    "lbl_nova_senha": "Nueva Contraseña:",
    "btn_salvar_perfil": "Guardar Cambios",
    "msg_senha_branco": "La contraseña no puede estar vacía.",
    "msg_perfil_ok": "¡Perfil actualizado!",
    "titulo_investimentos": "💹 Inversiones Corporativas",
    "lbl_usd": "Dólar (USD)",
    "carregando": "Cargando...",
    "lbl_eur": "Euro (EUR)",
    "registro_aquisicao": "Registrar Nueva Adquisición",
    "selecione_ativo": "Seleccione el Activo:",
    "preco_unitario": "Precio Unitario del Activo ($):",
    "saldo_calculando": "Saldo disponible: Calculando...",
    "qtd_comprar": "Cantidad a Comprar:",
    "ex_qtd": "Ej: 50",
    "btn_qtd_max": "Rellenar Cantidad Máxima",
    "btn_confirmar_inv": "Confirmar Inversión",
    "conversor_moedas": "💱 Conversor de Monedas Comercial",
    "ph_valor_brl": "Monto en BRL (R$)",
    "resultado_conv": "Resultado: ---",
    "btn_calcular_conv": "Calcular Conversión",
    "carteira_ativos": "📊 Su Cartera de Activos",
    "btn_rebalancear": "⚖️ Verificar Rebalanceo (Metas)",
    "btn_exportar_rel": "📥 Exportar Informe Patrimonial",
    "saldo_txt": "Saldo:",
    "max_permitido": "Máximo permitido:",
    "offline": "Desconectado",
    "erro_api": "Error API",
    "erro_conv_off": "Error: Conversor no disponible (Offline)",
    "msg_insira_brl": "Ingrese un monto en BRL para convertir.",
    "resultado_txt": "Resultado:",
    "msg_erro_num": "Ingrese solo caracteres numéricos válidos en el conversor.",
    "rebalanceamento": "Rebalanceo",
    "msg_carteira_vazia": "¡Su cartera está vacía! Sugerencia: Comience invirtiendo equitativamente en USD y EUR.",
    "msg_erro_rebal_api": "No se puede rebalancear sin acceso a cotizaciones de mercado.",
    "meta_cumprida_tit": "⚖️ ¡Meta Cumplida!",
    "msg_meta_cumprida": "¡Su cartera está perfectamente balanceada según las directrices!",
    "distribuicao_atual": "Distribución Actual:",
    "sugestao_rebal_tit": "⚖️ Sugerencia de Rebalanceo",
    "msg_desvio_detect": "Desvío detectado de las directrices ideales de asignación de riesgo (50%/50%).",
    "alocacao_atual": "Asignación Actual:",
    "recomendacao_rebal": "Recomendación: Dirija sus próximas inversiones a adquirir",
    "msg_erro_ativo_api": "Activo o cotización de la API inválidos.",
    "msg_preencha_tudo": "¡Complete todos los campos del formulario!",
    "msg_qtd_maior_zero": "¡La cantidad debe ser mayor a cero!",
    "saldo_insuficiente_tit": "Saldo Insuficiente",
    "msg_saldo_insuf": "¡No tiene suficiente saldo en cuenta para esta operación!",
    "custo_total": "Costo Total:",
    "msg_ativo_comprado": "¡Activo comprado!",
    "valor_debitado": "Monto debitado de la cuenta:",
    "msg_erro_num_qtd": "¡Ingrese solo números válidos en el campo de Cantidad!",
    "msg_carteira_vazia_label": "Aún no se han comprado activos.",
    "pago": "Pagado:",
    "total": "Total:",
    "relatorio_gerado_tit": "Informe Generado",
    "msg_relatorio_salvo": "El informe se ha guardado en su Escritorio.",
    "msg_enviar_email": "¿Desea enviar una copia al correo:",
    "btn_enviando_email": "📨 Enviando Correo...",
    "msg_email_enviado": "Informe enviado con éxito a",
    "erro_envio_tit": "Error de Envío",
    "msg_erro_envio": "El archivo se guardó localmente pero no se pudo enviar por correo:",
    "concluido": "Completado",
    "msg_relatorio_disp": "El informe está disponible en:",
    "erro_exportacao_tit": "Error de Exportación",
    "msg_aguarde_api": "Espere a que carguen las cotizaciones de la API."
}