# src/utils/lang_fr.py

TEXTOS_FR = {
    "painel_principal": "Tableau de Bord",
    "balanco_geral": "Bilan Général",
    "diag_financeiro": "Diagnostic Financier",
    "investimentos": "Investissements",
    "area_educacao": "Espace Éducation",
    "metas_financeiras": "Objectifs Financiers",
    "lembretes_contas": "Rappels de Factures",
    "editar_perfil": "Modifier le Profil",
    "btn_sair": "Se Déconnecter",
    "aviso": "Avertissement",
    "erro": "Erreur",
    "sucesso": "Succès",
    "titulo_login": "Bienvenue sur EasyFinance",
    "subtitulo_login": "Accédez à votre Compte Entreprise",
    "campo_email": "Entrez votre e-mail:",
    "campo_senha": "Entrez votre mot de passe:",
    "mostrar_senha": "Afficher le mot de passe",
    "btn_entrar": "Se Connecter",
    "saldo_atual": "Solde Actuel",
    "receitas_mes": "Revenus Mensuels",
    "despesas_mes": "Dépenses Mensuelles",
    "desempenho_b2b": "Votre Performance B2B",
    "pontuacao_tecnica": "Votre Score Technique",
    "nivel_perfil": "Niveau du Profil",
    "controle_teto_gastos": "Contrôle des Limites Budgétaires",
    "nenhum_gasto_monitoramento": "Aucune dépense enregistrée pour le suivi budgétaire.",
    "orcamento_estourado": "⚠️ BUDGET DÉPASSÉ !",
    "proximo_limite": "🟡 Près de la Limite",
    "dentro_do_teto": "🟢 Dans la Limite",
    "alerta_oportunidade_1": "Alerte de Coût d'Opportunité : Votre entreprise a",
    "alerta_oportunidade_2": "en dormant en liquidités.",
    "alerta_oportunidade_3": "Investir l'excédent",
    "alerta_oportunidade_4": "éviterait une perte estimée de",
    "fluxo_caixa": "Flux de Trésorerie et Transactions",
    "nenhuma_transacao": "Aucune transaction enregistrée.",
    "nova_movimentacao": "Nouvelle Transaction",
    "desc_exemplo": "Description (Ex : Marketing)",
    "valor_exemplo": "Montant (Ex : 1500.00)",
    "btn_registrar": "Enregistrer",
    "msg_preencha_dados": "Remplissez la description et le montant.",
    "msg_transacao_ok": "Transaction enregistrée !",
    "msg_erro_valor": "Entrez une valeur numérique valide.",
    "saude_relatorio": "Rapport de Santé Financière",
    "status_atual": "Statut Actuel :",
    "status_saudavel": "SAIN 🟢",
    "msg_saudavel": "Félicitations ! Votre entreprise est dans le vert.\nRecommandation : Envisagez d'investir l'excédent pour créer un fonds d'urgence.",
    "status_alerta": "EN ALERTE 🔴",
    "msg_alerta": "Attention ! Votre entreprise dépense plus qu'elle ne gagne.\nRecommandation : Vérifiez le 'Bilan Général' et réduisez les dépenses non essentielles.",
    "status_estavel": "STABLE 🟡",
    "msg_estavel": "Votre entreprise n'a ni profit ni perte actuellement.\nRecommandation : Concentrez-vous sur l'augmentation des ventes ou la création de nouvelles sources de revenus.",
    "titulo_educacao": "EasyFinance Academy - 20 Cours Disponibles",
    "btn_assistir": "Regarder",
    "titulo_metas": "Objectifs et Cibles de l'Entreprise",
    "nenhuma_meta": "Aucun objectif enregistré.",
    "alvo_meta": "Cible",
    "nova_meta": "Nouvel Objectif",
    "ex_meta_obj": "Ex : Nouveau Serveur",
    "ex_meta_val": "Ex : 5000.00",
    "btn_add_meta": "Ajouter l'Objectif",
    "msg_preencha_meta": "Remplissez l'objectif et la valeur de la cible.",
    "msg_meta_add": "Objectif financier ajouté !",
    "titulo_lembretes": "Rappels de Factures",
    "nenhum_lembrete": "Aucune facture à venir.",
    "vence_em": "Échéance le",
    "novo_lembrete": "Nouveau Rappel",
    "ex_conta": "Ex : Facture d'Électricité",
    "ex_data": "Ex : 10/06/2026",
    "btn_agendar": "Planifier la Facture",
    "msg_preencha_campos": "Veuillez remplir tous les champs.",
    "msg_lembrete_add": "Rappel programmé !",
    "config_conta": "Paramètres du Compte",
    "lbl_email": "E-mail (Connexion) :",
    "lbl_doc": "Document (Identité) :",
    "lbl_nova_senha": "Nouveau Mot de Passe :",
    "btn_salvar_perfil": "Enregistrer les Modifications",
    "msg_senha_branco": "Le mot de passe ne peut pas être vide.",
    "msg_perfil_ok": "Profil mis à jour !",
    "titulo_investimentos": "💹 Investissements d'Entreprise",
    "lbl_usd": "Dollar (USD)",
    "carregando": "Chargement...",
    "lbl_eur": "Euro (EUR)",
    "registro_aquisicao": "Enregistrer une Nouvelle Acquisition",
    "selecione_ativo": "Sélectionnez l'Actif :",
    "preco_unitario": "Prix Unitaire de l'Actif ($) :",
    "saldo_calculando": "Solde disponible : Calcul...",
    "qtd_comprar": "Quantité à Acheter :",
    "ex_qtd": "Ex : 50",
    "btn_qtd_max": "Remplir la Quantité Maximale",
    "btn_confirmar_inv": "Confirmer l'Investissement",
    "conversor_moedas": "💱 Convertisseur de Devises Commercial",
    "ph_valor_brl": "Montant en BRL (R$)",
    "resultado_conv": "Résultat : ---",
    "btn_calcular_conv": "Calculer la Conversion",
    "carteira_ativos": "📊 Votre Portefeuille d'Actifs",
    "btn_rebalancear": "⚖️ Vérifier le Rééquilibrage",
    "btn_exportar_rel": "📥 Exporter le Rapport de Patrimoine",
    "saldo_txt": "Solde :",
    "max_permitido": "Max autorisé :",
    "offline": "Hors ligne",
    "erro_api": "Erreur API",
    "erro_conv_off": "Erreur : Convertisseur indisponible (Hors ligne)",
    "msg_insira_brl": "Entrez un montant en BRL à convertir.",
    "resultado_txt": "Résultat :",
    "msg_erro_num": "Entrez uniquement des caractères numériques valides dans le convertisseur.",
    "rebalanceamento": "Rééquilibrage",
    "msg_carteira_vazia": "Votre portefeuille est vide ! Conseil : Commencez par investir également en USD et en EUR.",
    "msg_erro_rebal_api": "Impossible de rééquilibrer sans accès aux cotations boursières.",
    "meta_cumprida_tit": "⚖️ Objectif Atteint !",
    "msg_meta_cumprida": "Votre portefeuille est parfaitement équilibré selon les directives !",
    "distribuicao_atual": "Distribution Actuelle :",
    "sugestao_rebal_tit": "⚖️ Suggestion de Rééquilibrage",
    "msg_desvio_detect": "Écart détecté par rapport aux directives idéales de répartition des risques (50%/50%).",
    "alocacao_atual": "Allocation Actuelle :",
    "recomendacao_rebal": "Recommandation : Dirigez vos prochains investissements pour acquérir",
    "msg_erro_ativo_api": "Actif ou cotation de l'API invalide.",
    "msg_preencha_tudo": "Remplissez tous les champs du formulaire !",
    "msg_qtd_maior_zero": "La quantité doit être supérieure à zéro !",
    "saldo_insuficiente_tit": "Solde Insuffisant",
    "msg_saldo_insuf": "Vous n'avez pas un solde suffisant pour cette opération !",
    "custo_total": "Coût Total :",
    "msg_ativo_comprado": "Actif acheté !",
    "valor_debitado": "Montant débité du compte :",
    "msg_erro_num_qtd": "Entrez uniquement des nombres valides dans le champ Quantité !",
    "msg_carteira_vazia_label": "Aucun actif acheté pour le moment.",
    "pago": "Payé :",
    "total": "Total :",
    "relatorio_gerado_tit": "Rapport Généré",
    "msg_relatorio_salvo": "Le rapport a été enregistré sur votre Bureau.",
    "msg_enviar_email": "Souhaitez-vous envoyer une copie à l'e-mail :",
    "btn_enviando_email": "📨 Envoi de l'E-mail...",
    "msg_email_enviado": "Rapport envoyé avec succès à",
    "erro_envio_tit": "Erreur d'Envoi",
    "msg_erro_envio": "Le fichier a été enregistré localement mais n'a pas pu être envoyé par e-mail :",
    "concluido": "Terminé",
    "msg_relatorio_disp": "Le rapport est disponible à :",
    "erro_exportacao_tit": "Erreur d'Exportation",
    "msg_aguarde_api": "Veuillez patienter pendant le chargement des cotations de l'API.",
    "msg_adicional": "⚠️ Attention : Comme la date indiquée est déjà passée, le rappel a été marqué comme « Expiré » et une amende de R$ {VALOR_MULTA:.2f} a été débitée de votre solde !"
}